### ISSUE TITLE
Not responisve

### ISSUE THREAD

**Issue by syedfardeenjeelani** [anipr2002/hubql-clone#1]
not responsive for small screens

**Comment by anipr2002** [comment]
Not complete

**Comment by syedfardeenjeelani** [comment]
> Not complete

i made it responsive should i create pull request?

**Comment by anipr2002** [comment]
> > Not complete
> 
> i made it responsive should i create pull request?

Yup

**Comment by syedfardeenjeelani** [comment]
done
